/**
 * Browser-mode fallback: an explanatory modal + file picker.
 *
 * When `isTauri()` is false the generator can't run on-device (it
 * needs `claude` and a child process), but a user can still play a
 * campaign someone else generated by uploading the manifest.
 *
 * The modal:
 *   1. Explains the desktop-app limitation.
 *   2. Exposes a hidden `<input type="file">` triggered by a visible
 *      "Choose campaign.json…" button.
 *   3. On file selection: read → JSON.parse → parseCampaign.
 *   4. Resolves with one of:
 *        { kind: 'imported', manifestJson, path:'', seedUsed }
 *        { kind: 'closed' }
 *        { kind: 'error', errorClass: 'stdout-not-json' | 'schema-fail' }
 *
 * The harness owns the actual library-entry + theme + state transitions
 * — this module is just the picker + parse/validate.
 *
 * Companion: docs/architecture/procgen-integration.md §10.
 */

import { parseCampaign, CampaignParseError } from '../../schema/campaign';

export type BrowserFallbackResult =
  | { kind: 'imported'; manifestJson: string; path: string; seedUsed: string }
  | { kind: 'closed' }
  | { kind: 'error'; errorClass: 'stdout-not-json' | 'schema-fail'; message?: string };

export interface BrowserFallbackHandle {
  close(): void;
  result: Promise<BrowserFallbackResult>;
}

export function openBrowserFallback(host: HTMLElement): BrowserFallbackHandle {
  const dialog = document.createElement('dialog');
  dialog.dataset['role'] = 'browser-fallback-modal';
  dialog.style.cssText =
    'min-width: 420px; max-width: 560px; padding: 16px; border: 1px solid var(--muted); ' +
    'border-radius: 6px; background: var(--surface); color: var(--fg);';
  host.appendChild(dialog);

  let resolved = false;
  let resolveOuter!: (r: BrowserFallbackResult) => void;
  const resultPromise = new Promise<BrowserFallbackResult>((res) => {
    resolveOuter = res;
  });

  function finalize(r: BrowserFallbackResult): void {
    if (resolved) return;
    resolved = true;
    try {
      if (dialog.open) dialog.close();
    } catch {
      // jsdom safety
    }
    dialog.remove();
    resolveOuter(r);
  }

  const h = document.createElement('h2');
  h.textContent = 'New Campaign — desktop only';
  h.style.cssText = 'margin: 0 0 8px 0; font-size: 16px;';
  dialog.appendChild(h);

  const body = document.createElement('p');
  body.textContent =
    'The campaign generator runs on your machine via the Throughline desktop app. ' +
    'In a browser you can still play a campaign someone else generated — choose ' +
    'a campaign.json file below.';
  body.style.cssText = 'margin: 0 0 12px 0; white-space: pre-wrap;';
  dialog.appendChild(body);

  // Hidden file input + visible "Choose…" button.
  const fileInput = document.createElement('input');
  fileInput.type = 'file';
  fileInput.accept = 'application/json,.json';
  fileInput.dataset['role'] = 'file-input';
  fileInput.style.cssText = 'display: none;';
  dialog.appendChild(fileInput);

  const buttonRow = document.createElement('div');
  buttonRow.style.cssText = 'display: flex; gap: 8px; justify-content: flex-end;';
  dialog.appendChild(buttonRow);

  const cancelBtn = document.createElement('button');
  cancelBtn.type = 'button';
  cancelBtn.dataset['role'] = 'cancel';
  cancelBtn.textContent = 'Cancel';
  cancelBtn.style.cssText =
    'padding: 6px 14px; background: var(--bg); color: var(--fg); border: 1px solid var(--muted); border-radius: 4px; cursor: pointer; font: inherit;';
  cancelBtn.addEventListener('click', () => finalize({ kind: 'closed' }));
  buttonRow.appendChild(cancelBtn);

  const chooseBtn = document.createElement('button');
  chooseBtn.type = 'button';
  chooseBtn.dataset['role'] = 'choose-file';
  chooseBtn.textContent = 'Choose campaign.json…';
  chooseBtn.style.cssText =
    'padding: 6px 14px; background: var(--accent); color: var(--bg); border: 1px solid var(--accent); border-radius: 4px; cursor: pointer; font: inherit; font-weight: 600;';
  chooseBtn.addEventListener('click', () => fileInput.click());
  buttonRow.appendChild(chooseBtn);

  fileInput.addEventListener('change', () => {
    const file = fileInput.files?.[0];
    if (!file) return;
    void readAndValidate(file).then((r) => finalize(r));
  });

  try {
    dialog.showModal();
  } catch {
    // jsdom safety
  }

  return {
    close: () => finalize({ kind: 'closed' }),
    result: resultPromise,
  };
}

function readFileText(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (): void => resolve(String(reader.result ?? ''));
    reader.onerror = (): void => reject(reader.error ?? new Error('FileReader error'));
    reader.readAsText(file);
  });
}

async function readAndValidate(file: File): Promise<BrowserFallbackResult> {
  let text: string;
  try {
    text = await readFileText(file);
  } catch (e) {
    return { kind: 'error', errorClass: 'stdout-not-json', message: (e as Error).message };
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch (e) {
    return { kind: 'error', errorClass: 'stdout-not-json', message: (e as Error).message };
  }
  try {
    const manifest = parseCampaign(parsed);
    return {
      kind: 'imported',
      manifestJson: text,
      path: '',
      seedUsed: manifest.seed,
    };
  } catch (e) {
    const msg =
      e instanceof CampaignParseError
        ? `${e.message}\n${e.issues.join('\n')}`
        : (e as Error).message;
    return { kind: 'error', errorClass: 'schema-fail', message: msg };
  }
}
